---
title: "Team Amazing's Super Awesomely Outstanding Awesomeness"
author: "Anthony Gallegos, Abigail Henderson, Kendelle Brown"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: yes
---

```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE}
library(knitr)
library(dplyr)
library(pander)
library(devtools)
library(censusapi)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


# Load CensusAPI Package & Set CensusKey variable

```{r, echo=FALSE}
censuskey <- "e2a75a26c7d4adf9db476fa739110c582113d15e"
```


# Variable List (grabbed from our spreadsheets we filtered)
<!-- Once we've finalized our variables and come up with some kind of naming conventions, we are going to want to pull from Github instead of locally. -->

```{r}
# `1990_SF1_copy` <- read.csv("/home/anthony/Documents/Capstone/Cleaning/1990_SF1_copy.csv")
# var.list.sf1 <- `1990_SF1_copy`$name

`1990_race` <- read.csv("/home/anthony/Documents/Capstone/Cleaning/race_1990.csv")
var.list.race <- `1990_race`$name
```

# Data Pull

```{r}

# testing.SF1_1990 <- getCensus( name = "sf1", vintage = 1990, key=censuskey,
#                                vars = var.list.sf1,
#                                region="tract:*", regionin="state:04&county:13" )


testing.SF3_1990 <- getCensus( name = "sf3", vintage = 1990, key=censuskey,
                               vars = var.list.race,
                               region="tract:*", regionin="state:04&county:13" )

testing.SF3_1990 <- rename(testing.SF3_1990, White=P0080001, Black=P0080002, American_Indian_Eskimo_or_Aleu=P0080003, Asian_or_Pacific_Islander=P0080004, Other_Race=P0080005) 

write.csv( testing.SF3_1990, "/home/anthony/Documents/Capstone/Deliverables/1990_race_data", row.names=T)

```

# Allowable Geographies

```{r}
# geo_sf1_1990 <- listCensusMetadata( name= "sf1", vintage=1990, "g" )
# 
# geo_sf3_1990 <- listCensusMetadata( name= "sf3", vintage=1990, "g" )
```


#Reading in Vector file and converting to geojson

```{r}
library(maptools)
library(rgdal)
library(geojsonio)
library(rmapshaper)
# Note: This requires the package geojsonlint to be installed or you will get an error.
# 2010 shapefile downloaded from https://www.census.gov/geo/maps-data/data/tiger-line.html on 2/26/19.

# This command reads in the shapefile
maricopa <- readOGR(".", "tl_2010_04013_tract00")

# This command creates a json geofeaturecollection
maricopa2010 <- geojson_json(maricopa)

# Before writing the geofeaturecollection to a json format, we've got quite a few other steps.
maricopa_json_simplified <- ms_simplify(maricopa2010)


```


#Plotting

df <- data.frame(var=c("White", "Black", "American Indian, Eskimo, or Aleu", "Asian or Pacific Islander", "Other Race"))
plot2 <- ggplot(df, aes(x=var, scale_y_continuous( limits = c(0,1), expand = c(0,0) ))) + geom_bar(stat = "identity") 
print(plot2)




#Placeholder for Emoji violently ending itself
<!-- I will find one. -->

<par>
Placeholder


</par>
<br>
</br>

<par>




