---
title: "Team Amazing's Super Awesomely Outstanding Awesomeness"
author: "Anthony Gallegos, Abigail Henderson, Kendelle Brown"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: yes
---

```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE}
library(knitr)
library(dplyr)
library(pander)
library(devtools)
library(censusapi)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```


# Load CensusAPI Package & Set CensusKey variable

```{r, echo=FALSE}
censuskey <- "e2a75a26c7d4adf9db476fa739110c582113d15e"
```


# Variable List (grabbed from our spreadsheets we filtered)
<!-- Once we've finalized our variables and come up with some kind of naming conventions, we are going to want to pull from Github instead of locally. -->

```{r}
`1990_SF1_copy` <- read.csv("/home/anthony/Documents/Capstone/Cleaning/1990_SF1_copy.csv")
var.list.sf1 <- `1990_SF1_copy`$name

`1990_SF3_copy` <- read.csv("/home/anthony/Documents/Capstone/Cleaning/1990_SF3_copy.csv")
var.list.sf3 <- `1990_SF3_copy`$name
```

# Data Pull

```{r}

testing.SF1_1990 <- getCensus( name = "sf1", vintage = 1990, key=censuskey,
                               vars = var.list.sf1,
                               region="tract:*", regionin="state:04&county:13" )


testing.SF3_1990 <- getCensus( name = "sf3", vintage = 1990, key=censuskey,
                               vars = var.list.sf3,
                               region="tract:*", regionin="state:04&county:13" )

```

# Allowable Geographies

```{r}
geo_sf1_1990 <- listCensusMetadata( name= "sf1", vintage=1990, "g" )

geo_sf3_1990 <- listCensusMetadata( name= "sf3", vintage=1990, "g" )
```


#What's Next?

<par>
Placeholder

</par>
<br>
</br>


#Oh God There's More?

<par>
Placeholder

</par>
<br>
</br>

#Placeholder for Emoji violently ending itself
<!-- I will find one. -->

<par>
Placeholder


</par>
<br>
</br>

<par>




