---
title: "Replicating Race"
author: "Anthony Gallegos, Abigail Henderson, Kendelle Brown"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: yes
---

```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE}
library(knitr)
library(dplyr)
library(pander)
library(devtools)
library(censusapi)
library(maptools)
library(rgdal)
library(geojsonio)
library(rmapshaper)
library(sf)
library(ggplot2)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```




# Steps. It helps to just load all the libraries above at once.


```{r}

# Census Key
censuskey <- "e2a75a26c7d4adf9db476fa739110c582113d15e"

# Linux Paths

# Read csv file with all filtered variables. 
`1990_SF3_filtered` <- read.csv("/home/anthony/Documents/Capstone/Cleaning/1990_SF3_copy.csv")

# Read csv file with only race variables. I manually created this by cutting and pasting the rows I wanted from the previous spreadsheet. 
`1990_race` <- read.csv("/home/anthony/Documents/Capstone/Race/race_1990.csv")

# Create Variable list based off variables in the first column
var.list.race <- `1990_race`$name


# Pull Data using variable list only. Make sure the censusapi package is loaded.
race.pop <- getCensus( name = "sf3", vintage = 1990, key=censuskey,
                               vars = var.list.race,
                               region="tract:*", regionin="state:04&county:13" )

# Rename data
race.pop <- rename(race.pop, Total=P0010001, White=P0080001, Black=P0080002, American_Indian_Eskimo_or_Aleu=P0080003, Asian_or_Pacific_Islander=P0080004, Other_Race=P0080005)

# Write into new csv file
write.csv( race.pop, "/home/anthony/Documents/Capstone/Race/race_pop.csv", row.names=T)


# Import Shapefile
county_shp <- "/home/anthony/Documents/Capstone/2010/tl_2010_04013_tract00.shp"

# Read shape file and create and create variable for it
county_st <- st_read(county_shp)


# Join shapefile with race by tract
mcpa <- left_join(county_st, race.pop, by=c("TRACTCE00"="tract"))


# Mapping Total Population Density

# Blue map plot
ggplot(mcpa) + geom_sf(aes(fill=Total)) +  scale_fill_distiller(direction=1, name="Population") +
  labs(title="Maricopa County Population Concentrations", caption="1990 Source: US Census")


# Orange map plot
ggplot(mcpa) + 
  geom_sf(aes(fill=Total), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Oranges", direction=1, name="Population") +
  labs(title="Maricopa County Population Concentrations", caption="1990 Source: US Census")
```



#Reading in Vector file and converting to geojson 
<!-- Note this is useless unless I want to write the shapefile to geojson.. -->

```{r}
library(maptools)
library(rgdal)
library(geojsonio)
library(rmapshaper)

# Note: This requires the package geojsonlint to be installed or you will get an error.
# 2010 shapefile downloaded from https://www.census.gov/geo/maps-data/data/tiger-line.html on 2/26/19.
# This command reads in the shapefile
maricopa <- readOGR(".", "tl_2010_04013_tract00")
# This command creates a json geofeaturecollection
maricopa2010 <- geojson_json(maricopa)
# Before writing the geofeaturecollection to a json format, we've got quite a few other steps.
maricopa_json_simplified <- ms_simplify(maricopa2010)


# Or for existing...
county <- readOGR(dsn = "/Users/aggal/Desktop/Capstone/Maps/shapefiles/2010/county.geojson")




```



#Placeholder for Emoji violently ending itself
<!-- I will find one. -->

<par>
Placeholder


</par>
<br>
</br>

<par>
