---
title: "Income_2010_2015"
author: "Abby Henderson"
date: "3/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr, quietly=TRUE)
library(dplyr, quietly=TRUE)
library(pander, quietly=TRUE)
library(devtools, quietly=TRUE)
library(censusapi, quietly=TRUE)
library(maptools, quietly=TRUE)
library(rgdal, quietly=TRUE)
library(geojsonio, quietly=TRUE)
library(rmapshaper, quietly=TRUE)
library(sf, quietly=TRUE)
library(ggplot2, quietly=TRUE)
library(tidyr, quietly=TRUE)
library(viridis, quietly=TRUE)
library(gridExtra, quietly=TRUE)

censuskey <- "20f2773e863a33466e0fbace2116919a1c67e4a5"


## Global options
options(max.print="105")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=105)
```



```{r}

Metadata_2010_ACS5 <- read.csv("/Users/abigailhenderson/Desktop/Capstone/2010ACS5DataDictionary.csv")

#Read csv file with only race variables. I manually created this by cutting and pasting the rows I wanted from the previous spreadsheet. 
income_2010_vars <- read.csv("/Users/abigailhenderson/Desktop/Capstone/income_2010_vars.csv")

# Create Variable list based off variables in the first column
var.list.income.2010 <- income_2010_vars$name

income.pop.2010 <- getCensus( name = "acs/acs5", vintage = 2010, key=censuskey,
                               vars = var.list.income.2010,
                               region="tract:*", regionin="state:04&county:013" )


income.pop.2010 <- rename(income.pop.2010, Total_income_2010=B19001_001E,
                        Lessthan10k_2010=B19001_002E, 
                        TenkTo14k_2010=B19001_003E,
                        Fifteenkto20k_2010=B19001_004E,
                        TwentykTo25k_2010=B19001_005E, 
                        TwentyfivekTo30k_2010=B19001_006E, 
                        ThirtykTo35k_2010= B19001_007E,
                       ThirtyfivekTo40k_2010=B19001_008E,
                       FortykTo45k_2010=B19001_009E,
                       FortyfivekTo50k_2010=B19001_010E,
                       FiftykTo60k_2010=B19001_011E,
                       SixtykTo75k_2010=B19001_012E, 
                       SeventyfivekTo100k_2010=B19001_013E,
                       OnehundredkTo125k_2010=B19001_014E, 
                       OnetwentyfivekTo150k_2010=B19001_015E,
                       OnefiftykTo200k_2010=B19001_016E, 
                       TwohundredkPlus_2010=B19001_017E)



#Combine variable categories as necessary, including combining Male and Female to get a population count.

income.pop.2010 <- income.pop.2010 %>%
  mutate(OnetwentyfivekPlus_2010 = coalesce(OnehundredkTo125k_2010 + OnefiftykTo200k_2010 + TwohundredkPlus_2010))
```


```{r}
#Create percentage variables of each educational category

income.pop.2010 <- income.pop.2010 %>% group_by(tract) %>% 
  mutate((Lessthan10k_Percent_2010 = Lessthan10k_2010 / Total_income_2010) * 100) %>%
  mutate(( TenkTo14k_Percent_2010 = TenkTo14k_2010 / Total_income_2010) * 100) %>%
mutate(( TenkTo14k_Percent_2010 = TenkTo14k_2010 / Total_income_2010) * 100) %>% 
mutate(( Fifteenkto20k_Percent_2010 = Fifteenkto20k_2010 / Total_income_2010 ) * 100) %>%
mutate(( TwentykTo25k_Percent_2010 = TwentykTo25k_2010 / Total_income_2010 ) * 100) %>%
mutate(( TwentyfivekTo30k_Percent_2010 = TwentyfivekTo30k_2010 / Total_income_2010 ) * 100) %>%
mutate(( ThirtykTo35k_2010 = ThirtykTo35k_2010 / Total_income_2010 ) * 100) %>%
mutate(( ThirtyfivekTo40k_Percent_2010 = ThirtyfivekTo40k_2010  / Total_income_2010 ) * 100) %>%
mutate(( FortykTo45k_Percent_2010 = FortykTo45k_2010 / Total_income_2010 ) * 100) %>%
mutate(( FortyfivekTo50k_Percent_2010 = FortyfivekTo50k_2010 / Total_income_2010 ) * 100) %>%
mutate(( FiftykTo60k_Percent_2010 = FiftykTo60k_2010 / Total_income_2010 ) * 100) %>%
mutate(( SixtykTo75k_Percent_2010 = SixtykTo75k_2010 / Total_income_2010 ) * 100) %>%
mutate(( SeventyfivekTo100k_Percent_2010 = SeventyfivekTo100k_2010 / Total_income_2010 ) * 100) %>%
mutate(( OnehundredkTo125k_Percent_2010 = OnehundredkTo125k_2010 / Total_income_2010 ) * 100) %>%
mutate(( OnetwentyfivekTo150k_Percent_2010 = OnetwentyfivekTo150k_2010 / Total_income_2010 ) * 100) %>%
mutate(( OnefiftykTo200k_Percent_2010 = OnefiftykTo200k_2010 / Total_income_2010 ) * 100) %>%
mutate(( TwohundredkPlus_Percent_2010 = TwohundredkPlus_2010 / Total_income_2010 ) * 100)

#Write the data into a .csv file
write.csv( income.pop.2010, "/Users/abigailhenderson/Desktop/Capstone/income_pop_2010.csv", row.names=T)




# Import Shapefile
county_shp <- "/Users/abigailhenderson/Desktop/Capstone/tl_2010_04013_tract10/tl_2010_04013_tract10.shp"

# Read shape file and create and create variable for it
county_st <- st_read(county_shp)


#Create GEOID of FIPS Code elements
income_geoid_2010 <- paste0( income.pop.2010$state, income.pop.2010$county, income.pop.2010$tract)

income.pop.2010$geoid <- income_geoid_2010

# Join shapefile with race by tract
mcpa_income_2010 <- left_join(county_st, income.pop.2010, by=c("GEOID10"="geoid"))

# Mapping Total Population Density

# Purple map plot
ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=Total_income_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Maricopa County Population Concentrations", title.cex=.75, caption="2010 Source: US Census")

```



```{r}

#Small multiple maps of 2010 income categories
op <- par(mfrow=c(5,2))

p1_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill= Lessthan10k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Less than $10k", title.cex=0.5, caption="2010 Source: US Census")


p2_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=TwentykTo25k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $20,000 and $24,999", title.cex=0.5, caption="2010 Source: US Census")


p3_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=FortykTo45k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $40,000 and $44,999", title.cex=0.5, caption="2010 Source: US Census")

p4_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=FiftykTo60k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $50,000 and $59,999", title.cex=0.5, caption="2010 Source: US Census")

p5_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=SixtykTo75k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $60,000 and $74,999", title.cex=0.5, caption="2010 Source: US Census")

p6_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=SeventyfivekTo100k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $75,000 and $99,999", title.cex=0.5, caption="2010 Source: US Census")


p7_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=OnehundredkTo125k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $100,000 and $124,999", title.cex=0.5, caption="2010 Source: US Census")


p8_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=OnetwentyfivekTo150k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $125,000 and $149,999", title.cex=0.5, caption="2010 Source: US Census")
  
p9_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=OnefiftykTo200k_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $150,000 and $199,999", title.cex=0.5, caption="2010 Source: US Census")


p10_income_2010 <- ggplot(mcpa_income_2010) + 
  geom_sf(aes(fill=TwohundredkPlus_2010), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="$200,000 and Above", title.cex=0.5, caption="2015 Source: US Census")

grid.arrange( p1_income_2010, p2_income_2010, p3_income_2010, p4_income_2010, p5_income_2010, p6_income_2010, p7_income_2010, p8_income_2010, p9_income_2010, p10_income_2010, nrow=5)

```





```{r}


Metadata_2015_ACS5 <- read.csv("/Users/abigailhenderson/Desktop/Capstone/2015ACS5DataDictionary.csv")

#Read csv file with only race variables. I manually created this by cutting and pasting the rows I wanted from the previous spreadsheet. 
income_2015_vars <- read.csv("/Users/abigailhenderson/Desktop/Capstone/income_2015_vars.csv")

# Create Variable list based off variables in the first column
var.list.income.2015 <- income_2015_vars$name


# Pull Data using variable list only. Make sure the censusapi package is loaded.
income.pop.2015 <- getCensus( name = "acs/acs5", vintage = 2015, key=censuskey,
                               vars = var.list.income.2015,
                               region="tract:*", regionin="state:04&county:013" )

# Rename data
income.pop.2015 <- rename(income.pop.2015,
                      Total_income_2015=B19001_001E,
                        Lessthan10k_2015=B19001_002E, 
                        TenkTo14k_2015=B19001_003E,
                        Fifteenkto20k_2015=B19001_004E,
                        TwentykTo25k_2015=B19001_005E, 
                        TwentyfivekTo30k_2015=B19001_006E, 
                        ThirtykTo35k_2015= B19001_007E,
                       ThirtyfivekTo40k_2015=B19001_008E,
                       FortykTo45k_2015=B19001_009E,
                       FortyfivekTo50k_2015=B19001_010E,
                       FiftykTo60k_2015=B19001_011E,
                       SixtykTo75k_2015=B19001_012E, 
                       SeventyfivekTo100k_2015=B19001_013E,
                       OnehundredkTo125k_2015=B19001_014E, 
                       OnetwentyfivekTo150k_2015=B19001_015E,
                       OnefiftykTo200k_2015=B19001_016E, 
                       TwohundredkPlus_2015=B19001_017E)

#Combine Categories

income.pop.2015 <- income.pop.2015 %>%
  mutate(OnetwentyfivekPlus_2015 = coalesce(OnehundredkTo125k_2015 + OnefiftykTo200k_2015 + TwohundredkPlus_2015))


# Add Percentages


income.pop.2015 <- income.pop.2015 %>% group_by(tract) %>% 
  mutate((Lessthan10k_Percent_2015 = Lessthan10k_2015 / Total_income_2015) * 100) %>%
  mutate(( TenkTo14k_Percent_2015 = TenkTo14k_2015 / Total_income_2015) * 100) %>%
mutate(( TenkTo14k_Percent_2015 = TenkTo14k_2015 / Total_income_2015) * 100) %>% 
mutate(( Fifteenkto20k_Percent_2015 = Fifteenkto20k_2015 / Total_income_2015 ) * 100) %>%
mutate(( TwentykTo25k_Percent_2015 = TwentykTo25k_2015 / Total_income_2015 ) * 100) %>%
mutate(( TwentyfivekTo30k_Percent_2015 = TwentyfivekTo30k_2015 / Total_income_2015 ) * 100) %>%
mutate(( ThirtykTo35k_Percent_2015 = ThirtykTo35k_2015 / Total_income_2015 ) * 100) %>%
mutate(( ThirtyfivekTo40k_Percent_2015 = ThirtyfivekTo40k_2015  / Total_income_2015 ) * 100) %>%
mutate(( FortykTo45k_Percent_2015 = FortykTo45k_2015 / Total_income_2015 ) * 100) %>%
mutate(( FortyfivekTo50k_Percent_2015 = FortyfivekTo50k_2015 / Total_income_2015 ) * 100) %>%
mutate(( FiftykTo60k_Percent_2015 = FiftykTo60k_2015 / Total_income_2015 ) * 100) %>%
mutate(( SixtykTo75k_Percent_2015 = SixtykTo75k_2015 / Total_income_2015 ) * 100) %>%
mutate(( SeventyfivekTo100k_Percent_2015 = SeventyfivekTo100k_2015 / Total_income_2015 ) * 100) %>%
mutate(( OnehundredkTo125k_Percent_2015 = OnehundredkTo125k_2015 / Total_income_2015 ) * 100) %>%
mutate(( OnetwentyfivekTo150k_Percent_2015 = OnetwentyfivekTo150k_2015 / Total_income_2015 ) * 100) %>%
mutate(( OnefiftykTo200k_Percent_2015 = OnefiftykTo200k_2015 / Total_income_2015 ) * 100) %>%
mutate(( TwohundredkPlus_Percent_2015 = TwohundredkPlus_2015 / Total_income_2015 ) * 100)

# Write into new csv file
write.csv( income.pop.2015, "/Users/abigailhenderson/Desktop/Capstone/income_pop_2015.csv", row.names=T)


# Import Shapefile
county_shp <- "/Users/abigailhenderson/Desktop/Capstone/tl_2010_04013_tract10/tl_2010_04013_tract10.shp"

# Read shape file and create and create variable for it
county_st <- st_read(county_shp)


#Create GEOID of FIPS Code elements
income_geoid_2015 <- paste0( income.pop.2015$state, income.pop.2015$county, income.pop.2015$tract)

income.pop.2015$geoid <- income_geoid_2015

# Join shapefile with race by tract
mcpa_income_2015 <- left_join(county_st, income.pop.2015, by=c("GEOID10"="geoid"))


# Mapping Total Population Density

# Green map plot
ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=Total_income_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Maricopa County Population Concentrations", caption="2015 Source: US Census")
```
  
  
```{r}
#Small multiple maps of 2010 income categories
op <- par(mfrow=c(5,2))

p1_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill= Lessthan10k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Less than $10k", title.cex=0.5, caption="2015 Source: US Census")


p2_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=TwentykTo25k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $20,000 and $24,999", title.cex=0.5, caption="2015 Source: US Census")


p3_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=FortykTo45k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $40,000 and $44,999", title.cex=0.5, caption="2015 Source: US Census")

p4_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=FiftykTo60k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $50,000 and $59,999", title.cex=0.5, caption="2015 Source: US Census")

p5_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=SixtykTo75k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $60,000 and $74,999", title.cex=0.5, caption="2015 Source: US Census")

p6_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=SeventyfivekTo100k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $75,000 and $99,999", title.cex=0.5, caption="2015 Source: US Census")


p7_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=OnehundredkTo125k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $100,000 and $124,999", title.cex=0.5, caption="2015 Source: US Census")


p8_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=OnetwentyfivekTo150k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $125,000 and $149,999", title.cex=0.5, caption="2015 Source: US Census")
  
p9_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=OnefiftykTo200k_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="Between $150,000 and $199,999", title.cex=0.5, caption="2015 Source: US Census")


p10_income_2015 <- ggplot(mcpa_income_2015) + 
  geom_sf(aes(fill=TwohundredkPlus_2015), color="white") +
  theme_void() +
  theme(panel.grid.major = element_line(colour = 'transparent')) +
  scale_fill_distiller(palette="Purples", direction=1, name="Population") +
  labs(title="$200,000 and Above", title.cex=0.5, caption="2015 Source: US Census")

grid.arrange( p1_income_2015, p2_income_2015, p3_income_2015, p4_income_2015, p5_income_2015, p6_income_2015, p7_income_2015, p8_income_2015, p9_income_2015, p10_income_2015, nrow=5)
  
```
  
  